#ifndef __TOKENIZER_H
#define __TOKENIZER_H

#include <stdio.h>
#include <stdbool.h>

typedef struct
{
    char *src;
    size_t pos;
    size_t line;
    size_t col;
} Tokenizer;

typedef enum
{
    TERROR, TEND, TINVALID, TNUM, TIDENT, TCHARS, TSTRING,

    TORG, TUSE16, TUSE32,

    TAAA, TAAD, TAAM, TAAS, TADC, TADD, TAND, TCALL, TCBW, TCLC, TCLD, TCLI, TCMC, TCMP, TCMPSB, TCMPSW, TCWD, TDAA, TDAS, TDEC, TDIV, TESC, THLT, TIDIV, TIMUL, TIN, TINC, TINT, TINTO, TIRET, TJO, TJNO, TJB, TJNB, TJZ, TJNZ, TJBE, TJA, TJS, TJNS, TJPE, TJPO, TJL, TJGE, TJLE, TJG, TJCXZ, TJMP, TLAHF, TLDS, TLEA, TLES, TLOCK, TLODSB, TLODSW, TLOOP, TLOOPZ, LOOPNZ, TMOV, TMOVSB, TMOVSW, TMUL, TNEG, TNOP, TNOT, TOR, TOUT, TPOP, TPOPF, TPUSH, TPUSHF, TRCL, TRCR, TREPZ, TREPNZ, TRET, TRETF, TRETN, TROL, TROR, TSAHF, TSAL, TSAR, TSBB, TSCASB, TSCASW, TSHL, TSHR, TSTC, TSTD, TSTI, TSTOSB, TSTOSW, TSUB, TTEST, TWAIT, TXCHG, TXLAT, TXOR,

    TAX, TCX, TDX, TBX, TSP, TBP, TSI, TDI,
    TES, TCS, TSS, TDS,

    TLOGICALOR, TLOGICALAND,

    TQMARK, TCOLON, TCOMMA, TEQUALS, TNOTEQUALS, TGREATERTHANU, TGREATERTHANS, TLESSTHANU, TLESSTHANS, TGREATEREQUALSU, TGREATEREQUALSS, TLESSEQUALSU, TLESSEQUALSS, TSHIFTRIGHT, TSHIFTLEFT, TBITWISEXOR, TBITWISEOR, TBITWISEAND, TPLUS, TMINUS, TMODULOU, TMODULOS, TSLASHU, TSLASHS, TSTARU, TSTARS, TSTAR, TLEFTPAREN, TRIGHTPAREN
} TokenType;

typedef struct
{
    TokenType type;
    void *value;
} Token;

void tokenizer_init(Tokenizer *t, char *src);
TokenType tokenizer_token(Tokenizer *t, void *value);
TokenType die(Tokenizer *t, char *fmt, ...);

#endif