#ifndef __TOKENIZER_H
#define __TOKENIZER_H

#include <stdio.h>
#include <stdbool.h>

typedef struct
{
    char *src;
    size_t pos;
    size_t line;
    size_t col;
} Tokenizer;

typedef enum
{
    TERROR, TEND, TINVALID, TNUM, TIDENT, TCHARS, TSTRING,

    TORG, TUSE16, TUSE32, TDB, TDW, TDD, TRB, TBYTE, TWORD, TDWORD, TSHORT,

    TAAA, TAAD, TAAM, TAAS, TADC, TADD, TAND, TCALL, TCBW, TCLC, TCLD, TCLI, TCMC, TCMP, TCMPSB, TCMPSW, TCWDE, TCWD, TCDQ, TDAA, TDAS, TDEC, TDIV, TESC, THLT, TIDIV, TIMUL, TIN, TINC, TINT, TINTO, TIRET, TJO, TJNO, TJB, TJNB, TJZ, TJNZ, TJBE, TJA, TJS, TJNS, TJPE, TJPO, TJL, TJGE, TJLE, TJG, TJCXZ, TJMP, TLAHF, TLDS, TLEA, TLES, TLGDT, TLOCK, TLODSB, TLODSW, TLOOP, TLOOPZ, LOOPNZ, TMOV, TMOVSB, TMOVSW, TMOVSD, TMOVZX, TMUL, TNEG, TNOP, TNOT, TOR, TOUT, TPOPAD, TPOP, TPOPF, TPUSHAD, TPUSH, TPUSHF, TRCL, TRCR, TREP, TREPNZ, TRET, TRETF, TRETN, TROL, TROR, TSAHF, TSAL, TSAR, TSBB, TSCASB, TSCASW, TSETB, TSETZ, TSHL, TSHR, TSTC, TSTD, TSTI, TSTOSB, TSTOSW, TSTOSD, TSUB, TTEST, TWAIT, TXCHG, TXLAT, TXOR,

    TAX, TCX, TDX, TBX, TSP, TBP, TSI, TDI,
    TAL, TCL, TDL, TBL, TAH, TCH, TDH, TBH,
    TES, TCS, TSS, TDS, TFS, TGS,
    TEAX, TECX, TEDX, TEBX, TESP, TEBP, TESI, TEDI,
    TCR0, TCR1, TCR2, TCR3, TCR4, TCR5, TCR6, TCR7,

    TLOGICALOR, TLOGICALAND,

    TQMARK, TCOLON, TSEMICOLON, TCOMMA, TPLUSEQUALS, TMINUSEQUALS, TSHIFTLEFTEQUALS, TSHIFTRIGHTEQUALS, TBITWISEOREQUALS, TBITWISEXOREQUALS, TBITWISEANDEQUALS, TSLASHUEQUALS, TMODULOUEQUALS, TSTARUEQUALS, TEQUALS, TEQUALSEQUALS, TNOTEQUALS, TGREATERTHANU, TGREATERTHANS, TLESSTHANU, TLESSTHANS, TGREATEREQUALSU, TGREATEREQUALSS, TLESSEQUALSU, TLESSEQUALSS, TSHIFTRIGHT, TSHIFTLEFT, TBITWISEXOR, TBITWISEOR, TBITWISEAND, TBITWISENOT, TPLUS, TMINUS, TMODULOU, TMODULOS, TSLASHU, TSLASHS, TSTARU, TSTARS, TSTAR, TLEFTPAREN, TRIGHTPAREN, TLEFTBRACKET, TRIGHTBRACKET, TLEFTBRACE, TRIGHTBRACE, TLEFTCHEVRON, TRIGHTCHEVRON, TDOT, TBANG,

    TORIGIN, TIP, TPROGEND, TLINE, TFUNC,

    TINCLUDE, TFUNCTION, TCONST, TSTRUCT, TENUM, TGLOBAL, TRETURN, TIF, TELSE, TWHILE, TCONTINUE, TDO, TSWITCH, TCASE, TBREAK, TDEFAULT
} TokenType;

typedef struct
{
    TokenType type;
    void *value;
} Token;

void tokenizer_init(Tokenizer *t, char *src);
TokenType tokenizer_token(Tokenizer *t, void *value);
TokenType _die(char *file, int line, Tokenizer *t, char *fmt, ...);
#define die(...) _die(__FILE__, __LINE__, __VA_ARGS__)

#endif